apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-master
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /public/mysql-ms/m
    server: 192.168.0.170
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-master
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-master
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-master
  template:
    metadata:
      labels:
        name: mysql-master
        track: stable
    spec:
      containers:
        - image: paulliu/mysql-master:0.1
          name: mysql-master
          ports:
          - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
            - name: MYSQL_REPLICATION_USER
              value: "rep1"
            - name: MYSQL_REPLICATION_PASSWORD
              value: "123456"
          volumeMounts:
            - name: mysql-master-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-master-data
          persistentVolumeClaim:
            claimName: mysql-master
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  labels:
    name: mysql-master
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 31111
    protocol: TCP
  selector:
    name: mysql-master 
