apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-slave
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /public/mysql-ms/s
    server: 192.168.0.170
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-slave
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-slave
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-slave
  template:
    metadata:
      labels:
        name: mysql-slave
    spec:
      containers:
        - name: mysql-slave
          image: paulliu/mysql-slave:0.1
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
            - name: MYSQL_REPLICATION_USER
              value: "rep1"
            - name: MYSQL_REPLICATION_PASSWORD
              value: "123456"
           # - name: MYSQL_MASTER_SERVICE_HOST
           #   value: "192.168.0.170"
          volumeMounts:
            - name: mysql-slave-data
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
      volumes:
        - name: mysql-slave-data
          persistentVolumeClaim:
            claimName: mysql-slave
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
  labels:
    name: mysql-slave
spec:
    type: NodePort
    ports:
      - port: 3306
        targetPort: 3306
        nodePort: 31112
        protocol: TCP
    selector:
      name: mysql-slave
